project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Job Board"

  navbar:
    left:
      - href: index.qmd
        text: Summary

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



